scylla:
  datacenter: "us-east-1"
  racks:
  - name: "us-east-1a"
    scyllaConfig: scylla-config
    members: 3
    storage:
      capacity: 10Gi
    resources:
      limits:
        cpu: 1
        memory: 3Gi
      requests:
        cpu: 1
        memory: 3Gi
  serviceMonitor:
    create: true
  authenticator: AllowAllAuthenticator