certmanager:
  enabled: true
  namespace: "cert-manager"
  replicaCount: 1
scylla:
  datacenter: "us-east-1"
  racks:
  - name: "us-east-1a"
    scyllaConfig: scylla-config
    members: 3
    storage:
      capacity: 10Gi
    resources:
      limits:
        cpu: 1
        memory: 3Gi
      requests:
        cpu: 1
        memory: 3Gi
  serviceMonitor:
    create: true
prometheus:
  enabled: true
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: secret
    defaultDashboardsEnabled: true
    grafana.ini: {}
    image:
      repository: grafana/grafana
      tag: 7.5.11
      sha: ""
      pullPolicy: IfNotPresent