apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-hello-world.fullname" . }}
  labels:
    {{- include "nodejs-hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "nodejs-hello-world.selectorLabels" . | nindent 4 }}
